In [1]:
import pandas as pd
import numpy as np
import time
import datetime

In [2]:
dfc= pd.read_csv('chicago.csv')
dfn= pd.read_csv ('new_york_city.csv')
dfw= pd.read_csv ('washington.csv')
months= ['january','february','march','april','may','june','all',]
days= ['sunday','monday','tuesday','wednesday','thursday','friday','all',]

In [3]:
CITY_DATA = { 'chicago': 'chicago.csv',
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }

In [5]:
def get_filters():
    """
    Asks user to specify a city, month, and day to analyze.

    Returns:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    """
    # TO DO: get user input for city (chicago, new york city, washington). HINT: Use a while loop to handle invalid inputs
    print('Hello! Let\'s explore some US bikeshare data!')
    cities= ['chicago','new york city','washington']
    city= input("insert the name of the city: ").lower()
    
    # TO DO: get user input for month (all, january, february, ... , june)
    months= ['january','february','march','april','may','june']
    month= input("insert the name of the month : ").lower()

    while month not in months:
        month= input("oops!there was a typo! Please select any month from january to december: ").lower()


# TO DO: get user input for day of week (all, monday, tuesday, ... sunday)
    days= ['sunday','monday','tuesday','wednesday','thursday','friday']
    day= input("insert the name of the day : ").lower()

    while day not in days:
        day= input("oops!there was a typo! please select any day from sunday to saturday: ").lower()

    print('-'*40)
    return city, month, day

In [6]:
def load_data(city, month, day):
    """
    Loads data for the specified city and filters by month and day if applicable.

    Args:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    Returns:
        df - Pandas DataFrame containing city data filtered by month and day
    """
    df= pd.read_csv(CITY_DATA[city])
    
    #converting the data type of the 'Start Time' column into datetime
    df['Start Time'] = pd.to_datetime(df['Start Time'])
    df['month'] = df['Start Time'].dt.month # create a new column for 'month'
    df['day']= df['Start Time'].dt.dayofweek # create a new column for 'day' that consists the name of the week
    
    # use filter on the 'month' column to get the month and set Month's index starts from 1 to 6 
    if month != 'all':
        month= months.index(month)+1
        df= df[df['month']==month]
    # use filter on the 'day' column to get the day and set day's index starts from 1 to 7 
    if day != 'all':
        day= days.index(day)
        df= df[df['day']==day]
    return df

In [7]:
load_data('washington', 'january', 'monday').tail(5)

,Unnamed: 0,Start Time,End Time,Trip Duration,Start Station,End Station,User Type,month,day
299772,170450,2017-01-31 14:25:00,2017-01-31 14:35:00,632.366,5th & F St NW,M St & Delaware Ave NE,Subscriber,1,1
299777,172289,2017-01-31 17:41:00,2017-01-31 17:52:00,647.614,New Hampshire Ave & 24th St NW,New Hampshire Ave & T St NW,Subscriber,1,1
299785,167891,2017-01-31 07:56:00,2017-01-31 08:10:00,843.500,11th & M St NW,23rd & E St NW,Subscriber,1,1
299812,124017,2017-01-24 17:11:00,2017-01-24 17:18:00,418.341,4th & East Capitol St NE,19th & East Capitol St SE,Subscriber,1,1
299991,8834,2017-01-03 19:28:00,2017-01-03 19:40:00,714.928,Washington & Independence Ave SW/HHS,3rd & H St NE,Subscriber,1,1

In [10]:

def time_stats(df):
    """Displays statistics on the most frequent times of travel."""

    print('\nCalculating The Most Frequent Times of Travel...\n')
    start_time = time.time()

    # display the most common month
    common_month= df['month'].mode()[0]
    print('the most common month is: '.format(common_month))

    # display the most common day of week
    common_day= df['day'].mode()[0]
    print('the most common day is: '.format(common_day))
    
    # display the most common start hour
    df['hour'] = df['Start Time'].dt.hour # creating a column for Hour
    common_hour= df['hour'].mode()[0]
    print('the most common hour is: '.format(common_hour))
    
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [11]:
def station_stats(df):
    """Displays statistics on the most popular stations and trip."""

    print('\nCalculating The Most Popular Stations and Trip...\n')
    start_time = time.time()

    # most commonly used start station
    common_start_station= df ['Start Station'].mode()[0]
    print('the most common start station is: '.format(common_start_station))
    
    # most commonly used end station
    common_station= df ['End Station'].mode()[0]
    print('the most common station is: '.format(common_station))
    
    # most frequent combination of start station and end station trip
    station_combination = df ['Start Station'] + ' ' + df ['End Station'].mode()[0]
    print('the most most frequent combination of start station and end station trip is: '.format(station_combination))
   
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [12]:
def trip_duration_stats(df):
    """Displays statistics on the total and average trip duration."""

    print('\nCalculating Trip Duration...\n')
    start_time = time.time()

    # display total travel time
    total_travel= df['Trip Duration'].sum()
    print('Total travel time calculated is: '. format(total_travel))
    # display mean travel time
    mean_travel_time= df['Trip Duration'].mean()
    print('Total average travel time calculated is: '. format(mean_travel_time))
   
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [13]:
def user_stats(df,city):
    """Displays statistics on bikeshare users."""
    
    gender= ['Male','Female']
    
    print('\nCalculating User Stats...\n')
    
    start_time = time.time()

    # Display counts of user types
    user_type_count= df['User Type'].value_counts()
    print('The count of the different users numbers: '. format(user_type_count))
    
    # Display counts of gender
    if city != 'washington':
        print('Gender count is: {}'.format(df['Gender'].value_counts()))
    else:
        print('Please select any city but washington. We dont have data for Washington.')
        
    # Display earliest, most recent, and most common year of birth
    birth_year_earliest= int(df['Birth Year'].min())
    birth_year_recent= int(df['Birth Year'].max())
    birth_year_common= int(df['Birth Year'].mode()[0])
    if city !='washington':
        print ("the earliest,,recent and commont birth year {},{},{}.". format(birth_year_earliest,birth_year_recent,birth_year_common))
    else:
        print('birth_year for this {} is not available. Please select another city.'.format(city))
    
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [14]:
def display_data(df):
    index=0
    user_input=input('would you like to display 5 rows of raw data? ').lower()
    while user_input in ['yes','y','yep','yea'] and index+5 < df.shape[0]:
        print(df.iloc[index:index+5])
        index += 5
        user_input = input('would you like to display more 5 rows of raw data? ').lower()

In [15]:
def main():
    while True:
        city, month, day = get_filters()
        df = load_data(city, month, day)
        time_stats(df)
        station_stats(df)
        trip_duration_stats(df)
        user_stats(df,city)
        display_data(df)
        
        restart = input('\nWould you like to restart? Enter yes or no.\n')
        if restart.lower() != 'yes':
            break


if __name__ == "__main__":
	main()

Hello! Let's explore some US bikeshare data!
insert the name of the city: Chicago
insert the name of the month : January
insert the name of the day : Sunday
----------------------------------------

Calculating The Most Frequent Times of Travel...

the most common month is:
the most common day is:
the most common hour is:

This took 0.0 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

the most common start station is:
the most common station is:
the most most frequent combination of start station and end station trip is:

This took 0.02034592628479004 seconds.
----------------------------------------

Calculating Trip Duration...

Total travel time calculated is:
Total average travel time calculated is:

This took 0.0009753704071044922 seconds.
----------------------------------------

Calculating User Stats...

The count of the different users numbers:
Gender count is: Male      2728
Female     687
Name: Gender, dtype: int64
the earliest,,recent and commont birth year 1934,1999,1989.

This took 0.00498652458190918 seconds.
----------------------------------------
would you like to display 5 rows of raw data? yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
121       42280 2017-01-16 14:54:38  2017-01-16 15:09:03            865
167       77795 2017-01-23 18:50:16  2017-01-23 18:56:43            387
236       42046 2017-01-16 11:29:52  2017-01-16 11:43:56            844
253       73287 2017-01-23 07:21:14  2017-01-23 07:32:39            685
256        3680 2017-01-02 23:40:20  2017-01-02 23:45:25            305

                     Start Station                        End Station  \
121                   Field Museum                    Millennium Park
167     Indiana Ave & Roosevelt Rd       Michigan Ave & Washington St
236  Pine Grove Ave & Waveland Ave  Ravenswood Ave & Montrose Ave (*)
253      Artesian Ave & Hubbard St    Racine Ave (May St) & Fulton St
256    Lincoln Ave & Diversey Pkwy          Lincoln Ave & Belmont Ave

      User Type  Gender  Birth Year  month  day  hour
121  Subscriber    Male      1992.0      1    0    14
167  Subscriber    Male      1990.0      1    0    18
236  Subscriber  Female      1990.0      1    0    11
253  Subscriber    Male      1972.0      1    0     7
256  Subscriber    Male      1987.0      1    0    23
would you like to display more 5 rows of raw data? yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
496        2337 2017-01-02 11:28:54  2017-01-02 11:46:50           1076
579       76688 2017-01-23 17:10:46  2017-01-23 17:17:47            421
634      106343 2017-01-30 19:11:40  2017-01-30 19:19:15            455
683       21541 2017-01-09 14:58:30  2017-01-09 15:06:32            482
894       21264 2017-01-09 12:57:39  2017-01-09 13:00:54            195

                    Start Station                      End Station  \
496     Desplaines St & Kinzie St        Desplaines St & Kinzie St
579  Financial Pl & Congress Pkwy        Wabash Ave & Roosevelt Rd
634  Michigan Ave & Washington St            Canal St & Madison St
683           Wells St & Huron St        Clinton St & Jackson Blvd
894       Broadway & Waveland Ave  Pine Grove Ave & Irving Park Rd

      User Type Gender  Birth Year  month  day  hour
496  Subscriber   Male      1985.0      1    0    11
579  Subscriber   Male      1991.0      1    0    17
634  Subscriber   Male      1986.0      1    0    19
683  Subscriber   Male      1976.0      1    0    14
894  Subscriber   Male      1986.0      1    0    12
would you like to display more 5 rows of raw data? no

Would you like to restart? Enter yes or no.
no